"use client";

import { History, Play, RefreshCw, ShieldCheck, Warehouse } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { InventoryDetail } from "@/components/inventory/inventory-detail";
import { InventoryMatrix } from "@/components/inventory/inventory-matrix";
import { createInventory, getInventoryPortfolio, getInventoryRun, listInventoryForecasts, listInventoryPortfolios, listInventoryRuns, listInventoryScenarios, preflightInventory, regenerateInventoryDemo } from "@/lib/inventory-api";
import { inventoryDemoDraft, inventoryDemoPortfolio, inventoryDemoSources, inventoryRunFromSearch, inventoryRunUrl, inventoryWorkspaceFromRun } from "@/lib/inventory-handoff";
import type { ForecastRunSummary, InventoryDraft, InventoryInputName, InventoryItem, InventoryPreflight, InventoryRun, InventoryRunSummary, PortfolioRunSummary, ScenarioRunSummary } from "@/lib/inventory-types";
import { translateFrequency, ui } from "@/lib/i18n";

const fields: InventoryInputName[] = ["inventory_on_hand", "inventory_in_transit", "safety_stock", "lead_time", "service_level", "unit_cost", "order_cost", "holding_cost", "holding_rate", "moq", "lot_multiple", "capacity", "committed_inventory", "backorders"];
const emptyDraft = () => Object.fromEntries(fields.map((field) => [field, ""])) as InventoryDraft;
const toLocal = (date: Date) => { const local = new Date(date); local.setMinutes(local.getMinutes() - local.getTimezoneOffset()); return local.toISOString().slice(0, 16); };
const fmt = (value: number | null) => value == null ? "—" : new Intl.NumberFormat("es-PE", { maximumFractionDigits: 1 }).format(value);

export function InventoryWorkspace() {
  const copy = ui.inventory;
  const [forecasts, setForecasts] = useState<ForecastRunSummary[]>([]);
  const [scenarios, setScenarios] = useState<ScenarioRunSummary[]>([]);
  const [portfolios, setPortfolios] = useState<PortfolioRunSummary[]>([]);
  const [history, setHistory] = useState<InventoryRunSummary[]>([]);
  const [forecastId, setForecastId] = useState(""); const [scenarioId, setScenarioId] = useState(""); const [portfolioId, setPortfolioId] = useState("");
  const [cutoff, setCutoff] = useState(""); const [includeTransit, setIncludeTransit] = useState(false); const [draft, setDraft] = useState<InventoryDraft>(emptyDraft);
  const [preflight, setPreflight] = useState<InventoryPreflight | null>(null); const [run, setRun] = useState<InventoryRun | null>(null); const [selected, setSelected] = useState<InventoryItem | null>(null);
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState<string | null>(null);
  const selectedForecast = forecasts.find((item) => item.id === forecastId) ?? null;
  const compatibleScenarios = useMemo(() => scenarios.filter((item) => item.forecast_run_id === forecastId && item.status === "completed"), [scenarios, forecastId]);

  useEffect(() => { let active = true; const requested = inventoryRunFromSearch(window.location.search); Promise.all([listInventoryForecasts(), listInventoryScenarios(), listInventoryPortfolios(), listInventoryRuns()]).then(async ([forecastItems, scenarioItems, portfolioItems, runs]) => { if (!active) return; const completedForecasts = forecastItems.filter((item) => item.status === "completed"); setForecasts(completedForecasts); setScenarios(scenarioItems); setPortfolios(portfolioItems); setHistory(runs); setForecastId(completedForecasts[0]?.id ?? ""); setCutoff(toLocal(new Date())); if (requested && runs.some((item) => item.id === requested)) { const stored = await getInventoryRun(requested); if (!active) return; const workspace = inventoryWorkspaceFromRun(stored, fields); setForecastId(completedForecasts.some((item) => item.id === workspace.forecastId) ? workspace.forecastId : ""); setScenarioId(scenarioItems.some((item) => item.id === workspace.scenarioId && item.forecast_run_id === workspace.forecastId) ? workspace.scenarioId : ""); setPortfolioId(portfolioItems.some((item) => item.id === workspace.portfolioId) ? workspace.portfolioId : ""); setCutoff(toLocal(new Date(workspace.cutoff))); setIncludeTransit(workspace.includeTransit); setDraft(workspace.draft as InventoryDraft); setRun(stored); setSelected(stored.items[0] ?? null); } }).catch((cause: Error) => active && setError(cause.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);

  const payload = () => ({ forecastRunId: forecastId, scenarioRunId: scenarioId || null, portfolioRunId: portfolioId || null, cutoff: new Date(cutoff).toISOString(), draft, includeInTransit: includeTransit, frequency: selectedForecast?.frequency });
  const setUrl = (id: string) => window.history.replaceState(null, "", inventoryRunUrl(id));
  async function validate() { if (!forecastId || !cutoff) return; setWorking(true); setError(null); try { setPreflight(await preflightInventory(payload())); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.error); } finally { setWorking(false); } }
  async function execute() { if (!forecastId || !cutoff) return; setWorking(true); setError(null); try { const result = await createInventory(payload()); setRun(result); setSelected(result.items[0] ?? null); setPreflight(null); setUrl(result.id); setHistory(await listInventoryRuns()); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.error); } finally { setWorking(false); } }
  async function demo() { setWorking(true); setError(null); try { const sources = inventoryDemoSources(forecasts, scenarios); if (!sources) throw new Error(copy.actions.demoUnavailable); const portfolioDetails = await Promise.all(portfolios.filter((item) => item.source_mode === "official").map((item) => getInventoryPortfolio(item.id))); const exactPortfolioId = inventoryDemoPortfolio(portfolioDetails, sources.forecastId); if (!exactPortfolioId) throw new Error(copy.actions.demoUnavailable); const result = await regenerateInventoryDemo(); setForecastId(sources.forecastId); setScenarioId(sources.scenarioId); setPortfolioId(exactPortfolioId); setCutoff(toLocal(new Date())); setIncludeTransit(true); setDraft(inventoryDemoDraft() as InventoryDraft); setPreflight(null); setRun(result); setSelected(result.items[0] ?? null); setUrl(result.id); setHistory(await listInventoryRuns()); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.error); } finally { setWorking(false); } }
  async function openStored(id: string) { setWorking(true); setError(null); try { const result = await getInventoryRun(id); const workspace = inventoryWorkspaceFromRun(result, fields); setForecastId(forecasts.some((item) => item.id === workspace.forecastId) ? workspace.forecastId : ""); setScenarioId(scenarios.some((item) => item.id === workspace.scenarioId && item.forecast_run_id === workspace.forecastId) ? workspace.scenarioId : ""); setPortfolioId(portfolios.some((item) => item.id === workspace.portfolioId) ? workspace.portfolioId : ""); setCutoff(toLocal(new Date(workspace.cutoff))); setIncludeTransit(workspace.includeTransit); setDraft(workspace.draft as InventoryDraft); setPreflight(null); setRun(result); setSelected(result.items[0] ?? null); setUrl(result.id); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.error); } finally { setWorking(false); } }
  if (loading) return <div className="workspace iv-workspace"><div className="iv-loading"><RefreshCw size={18} />{copy.loading}</div></div>;
  return <div className="workspace iv-workspace"><header className="workspace-header iv-header"><div><span className="eyebrow">{copy.header.eyebrow}</span><h1>{copy.header.title}</h1><p>{copy.header.subtitle}</p></div><div className="iv-boundary"><ShieldCheck size={18} /><span>{copy.header.boundary}<strong>{copy.header.noExecution}</strong></span></div></header>
    <section className="iv-panel"><div className="iv-heading"><div><span>{copy.scope.index}</span><h2>{copy.scope.title}</h2></div>{preflight && <b className={`iv-status iv-status--${preflight.readiness}`}>{preflight.readiness === "ready" ? copy.scope.ready : copy.scope.warning}</b>}</div><div className="iv-sources"><label><span>{copy.scope.forecast}</span><select value={forecastId} onChange={(event) => { setForecastId(event.target.value); setScenarioId(""); setPreflight(null); }}>{forecasts.map((item) => <option key={item.id} value={item.id}>{item.id.slice(0, 8)} · {translateFrequency(item.frequency)} · {item.requested_horizon} · {item.champion_model}</option>)}</select></label><label><span>{copy.scope.scenario}</span><select value={scenarioId} onChange={(event) => { setScenarioId(event.target.value); setPreflight(null); }}><option value="">{copy.scope.none}</option>{compatibleScenarios.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.id.slice(0, 8)}</option>)}</select></label><label><span>{copy.scope.portfolio}</span><select value={portfolioId} onChange={(event) => { setPortfolioId(event.target.value); setPreflight(null); }}><option value="">{copy.scope.none}</option>{portfolios.map((item) => <option key={item.id} value={item.id}>{item.source_mode === "demo" ? copy.history.demo : item.id.slice(0, 8)} · {item.number_of_series} series</option>)}</select></label><label><span>{copy.scope.cutoff}</span><input type="datetime-local" value={cutoff} onChange={(event) => { setCutoff(event.target.value); setPreflight(null); }} /></label></div><label className="iv-check"><input type="checkbox" checked={includeTransit} onChange={(event) => { setIncludeTransit(event.target.checked); setPreflight(null); }} />{copy.scope.transit}</label>
      <div className="iv-input-head"><span>{copy.inputs.index}</span><h3>{copy.inputs.title}</h3><p>{copy.inputs.note}</p></div><div className="iv-input-grid">{fields.map((field) => <label key={field}><span>{copy.inputs[field]}</span><input type="number" min="0" step="any" placeholder={copy.missing} value={draft[field]} onChange={(event) => { setDraft((current) => ({ ...current, [field]: event.target.value })); setPreflight(null); }} /></label>)}</div>{preflight && <div className="iv-preflight"><strong>{Object.values(preflight.calculable).filter(Boolean).length}/{Object.keys(preflight.calculable).length} cálculos disponibles</strong><span>{preflight.missing_inputs.length} inputs ausentes · fuente {preflight.demand_source}</span></div>}{error && <div className="ds-error-message">{error}</div>}<div className="iv-actions"><button className="iv-secondary" type="button" disabled={working} onClick={() => void demo()}><Warehouse size={16} />{working ? copy.actions.demoLoading : copy.actions.demo}</button><button className="iv-secondary" type="button" disabled={working || !forecastId} onClick={() => void validate()}>{copy.scope.validate}</button><button className="iv-primary" type="button" disabled={working || !forecastId} onClick={() => void execute()}><Play size={16} />{working ? copy.scope.running : copy.scope.run}</button></div></section>
    {run && <><section className="iv-kpis">{[[copy.summary.series, run.summary.series_analyzed], [copy.summary.attention, run.summary.risk_counts.critical + run.summary.risk_counts.high], [copy.summary.shortage, fmt(run.summary.projected_shortage)], [copy.summary.surplus, fmt(run.summary.projected_surplus)], [copy.summary.calculable, run.summary.calculable_recommendations], [copy.summary.review, run.summary.manual_review_required], [copy.summary.completeness, `${run.summary.input_completeness}%`]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section><InventoryMatrix items={run.items} selectedId={selected?.id ?? null} onSelect={setSelected} /><InventoryDetail item={selected} run={run} /></>}
    <section className="iv-panel"><div className="iv-heading"><div><span>{copy.history.index}</span><h2>{copy.history.title}</h2></div><History size={17} /></div>{history.length ? <div className="iv-history">{history.map((item) => <button key={item.id} type="button" onClick={() => void openStored(item.id)}><span><strong>{new Date(item.created_at).toLocaleString("es-PE")}</strong><small>{item.source_mode === "demo" ? copy.history.demo : item.forecast_run_id}</small></span><b>{copy.history.open}</b></button>)}</div> : <p className="iv-muted">{copy.history.empty}</p>}</section></div>;
}
