"""Extensible action catalog and stable tie-break order."""

ACTION_ORDER = (
    "review_stockout_risk",
    "review_scor_critical",
    "review_scor_deliver",
    "review_scor_source",
    "review_scor_make",
    "review_scor_plan",
    "review_scor_return",
    "complete_scor_evidence",
    "review_portfolio_coverage",
    "review_portfolio_priority",
    "review_portfolio_volatility",
    "complete_portfolio_data",
    "manual_review_required",
    "prepare_supply",
    "prepare_capacity",
    "review_replenishment",
    "investigate_demand_increase",
    "investigate_demand_drop",
    "review_inventory_policy",
    "review_promotion_plan",
    "review_price_change",
    "maintain_plan",
    "monitor",
)

ACTION_LABELS = {
    "monitor": "Monitorear evolución",
    "maintain_plan": "Mantener el plan bajo observación",
    "prepare_supply": "Preparar revisión de abastecimiento",
    "prepare_capacity": "Revisar preparación de capacidad",
    "review_replenishment": "Revisar el plan de reposición",
    "review_inventory_policy": "Revisar la política de inventario",
    "investigate_demand_drop": "Investigar el descenso de demanda",
    "investigate_demand_increase": "Investigar el incremento de demanda",
    "review_stockout_risk": "Revisar riesgo de ruptura de stock",
    "review_promotion_plan": "Revisar el plan promocional",
    "review_price_change": "Revisar el cambio de precio",
    "manual_review_required": "Revisión manual requerida",
    "review_scor_critical": "Revisar proceso crítico candidato",
    "review_scor_plan": "Revisar desempeño de planificación",
    "review_scor_source": "Revisar desempeño de abastecimiento",
    "review_scor_make": "Revisar producción y almacenaje",
    "review_scor_deliver": "Revisar desempeño de distribución",
    "review_scor_return": "Revisar desempeño de retornos",
    "complete_scor_evidence": "Completar evidencia operativa SCOR",
    "review_portfolio_coverage": "Revisar cobertura de inventario",
    "review_portfolio_priority": "Revisar serie priorizada del portafolio",
    "review_portfolio_volatility": "Revisar exposición por variabilidad",
    "complete_portfolio_data": "Completar datos operativos de inventario",
}

PRIORITY_WEIGHT = {"critical": 4, "high": 3, "medium": 2, "low": 1}
